### PR TITLE
Send heartrate, floor, and respiration rate values to Home Assistant

### PR DESCRIPTION
**Pull request by KPWhiver**
This change sends the heartrate, respiration rate, stepcount, and floors climbed/descended to Home Assistant as mobile app entities. There are a lot more sensors that could potentially be added.

I have only tested this on a Vivoactive 4s as that is the only device I own.

Let me know what you think and if there are any changes you would like to see.

### CODE REVIEW

**Comment by philipabbey** [comment]
Apologies, I've only just seen this. I'll take a look.

**Comment by philipabbey** [comment]
Again apologies, as a bug fix has upset the merge by causing a conflict. It should be as simple as a single condition involving

```monkey
if (System.getDeviceSettings().phoneConnected) {
} else {
}
```

**Comment by philipabbey** [comment]
I'm compiling this for a private beta test on my Venu2 watch. I'll sort out that merge conflict and commit back to this branch if that's okay with you?

I am curious as to how you'll make use of these newly reported values on your Home Assistant.

**Comment by philipabbey** [comment]
All working on my Beta app.

**Comment by philipabbey** [comment]
@KPWhiver Are you happy with my small amendments?

**Comment by KPWhiver** [comment]
Yes looks good

**Pull request merged**
